# Generated by Django 2.2.7 on 2019-12-01 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opciones', '0006_auto_20191201_0146'),
        ('peliculas', '0002_auto_20191126_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='languages',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='opciones.Language', verbose_name='Idioma'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='duration',
            field=models.TimeField(verbose_name='Duración'),
        ),
    ]
