# Generated by Django 2.2.7 on 2019-12-01 11:13

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('opciones', '0006_auto_20191201_0146'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=100, verbose_name='Género')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Género Musical',
                'verbose_name_plural': 'Géneros Musicales',
                'ordering': ['genre'],
            },
        ),
        migrations.CreateModel(
            name='TrackList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track', models.CharField(max_length=150, verbose_name='Canción')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opciones.Music', verbose_name='Banda / Compositor')),
            ],
            options={
                'verbose_name': 'Cancion',
                'verbose_name_plural': 'Lista de canciones',
                'ordering': ['created', 'track'],
            },
        ),
        migrations.CreateModel(
            name='MusicDiscs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(upload_to='musica/caratulas', verbose_name='Carátula')),
                ('title', models.CharField(max_length=150, verbose_name='Album')),
                ('release', models.DateField(verbose_name='Fecha de lanzamiento')),
                ('duration', models.TimeField(verbose_name='Duración')),
                ('numer_discs', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=10, verbose_name='Número de discos')),
                ('info', ckeditor.fields.RichTextField(verbose_name='Información del disco')),
                ('as_downloaded', models.BooleanField(default=False, verbose_name='Subido')),
                ('download_link', models.URLField(blank=True, verbose_name='Link de Descarga')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opciones.Music', verbose_name='Banda / Compositor')),
                ('genre', models.ManyToManyField(to='music.MusicGenre', verbose_name='Género Musical')),
                ('produced', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opciones.Produced', verbose_name='Productora')),
                ('songs', models.ManyToManyField(to='music.TrackList', verbose_name='Lista de canciones')),
            ],
            options={
                'verbose_name': 'Música',
                'verbose_name_plural': 'Discos de Música',
                'ordering': ['title'],
            },
        ),
    ]
