# Generated by Django 2.2.7 on 2019-11-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opciones', '0004_director_guion_music'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Reparto')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Reparto',
                'verbose_name_plural': 'Actores',
                'ordering': ['name'],
            },
        ),
    ]
