# Generated by Django 2.2.7 on 2019-12-01 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opciones', '0005_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='music',
            options={'ordering': ['name'], 'verbose_name': 'Compositor / Banda', 'verbose_name_plural': 'Compositores / Bandas'},
        ),
        migrations.AlterField(
            model_name='music',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Compositor / Banda'),
        ),
    ]
