# Generated by Django 2.2.7 on 2019-11-24 13:31

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('opciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Título')),
                ('poster', models.ImageField(upload_to='series/posters/', verbose_name='Poster')),
                ('first_emission', models.DateField(verbose_name='Primera Emisión')),
                ('last_emission', models.DateField(verbose_name='Última Emisión')),
                ('episodes', models.IntegerField(verbose_name='Episodios')),
                ('seassons', models.IntegerField(verbose_name='Temporadas')),
                ('plot', ckeditor.fields.RichTextField(verbose_name='Sipnosis')),
                ('screen_one', models.ImageField(upload_to='series/posters/', verbose_name='Captura uno')),
                ('screen_two', models.ImageField(upload_to='series/posters/', verbose_name='Captura dos')),
                ('screen_three', models.ImageField(upload_to='series/posters/', verbose_name='Captura tres')),
                ('screen_four', models.ImageField(upload_to='series/posters/', verbose_name='Captura cuatro')),
                ('link', models.URLField(verbose_name='Enlace de descarga')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opciones.Category', verbose_name='Categoría')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opciones.Artist', verbose_name='Creado por')),
                ('genre', models.ManyToManyField(to='opciones.Genre', verbose_name='Género')),
                ('studio', models.ManyToManyField(to='opciones.Studio', verbose_name='Estudio')),
            ],
            options={
                'verbose_name': 'Serie',
                'verbose_name_plural': 'Series',
                'ordering': ['title', 'first_emission'],
            },
        ),
    ]
