# Generated by Django 2.2.7 on 2019-11-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='as_downloaded',
            field=models.BooleanField(default=False, verbose_name='Subido'),
        ),
    ]
