# Generated by Django 2.2.7 on 2019-11-24 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opciones', '0002_resolution'),
        ('series', '0002_serie_as_downloaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='duration',
            field=models.IntegerField(default=1, verbose_name='Duración por episodio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serie',
            name='encoding',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='opciones.Extension', verbose_name='Formato de video'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serie',
            name='peso',
            field=models.IntegerField(default=1, verbose_name='Peso por archivo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serie',
            name='resolution',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='opciones.Resolution', verbose_name='Resolución'),
            preserve_default=False,
        ),
    ]
