# Generated by Django 2.2.7 on 2019-12-01 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opciones', '0006_auto_20191201_0146'),
        ('series', '0005_auto_20191201_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='languages',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='opciones.Language', verbose_name='Idioma'),
            preserve_default=False,
        ),
    ]
