# Generated by Django 2.2.7 on 2019-12-01 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opciones', '0006_auto_20191201_0146'),
        ('series', '0006_serie_languages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serie',
            name='studio',
        ),
        migrations.AddField(
            model_name='serie',
            name='studio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='opciones.Studio', verbose_name='Estudio'),
            preserve_default=False,
        ),
    ]
