# Generated by Django 2.2.7 on 2019-11-28 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retrojuegos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='console',
            name='console_banner',
            field=models.ImageField(blank=True, upload_to='videoconsolas/banner/', verbose_name='Banner'),
        ),
        migrations.AddField(
            model_name='console',
            name='console_image',
            field=models.ImageField(blank=True, upload_to='videoconsolas/foto/', verbose_name='Foto de Consola'),
        ),
    ]
