# Generated by Django 3.0.1 on 2020-01-29 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retrojuegos', '0002_auto_20191128_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='retrojuego',
            name='video',
            field=models.FileField(blank=True, upload_to='retrogames/videosnaps', verbose_name='Video'),
        ),
    ]
