# Generated by Django 3.0.1 on 2020-02-22 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retrojuegos', '0003_retrojuego_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='retrojuego',
            name='logo',
            field=models.ImageField(blank=True, upload_to='retrogames/logo', verbose_name='Logotipo'),
        ),
    ]
