# Generated by Django 3.0.1 on 2020-07-08 21:17

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opciones', '0006_auto_20191201_0146'),
        ('retrojuegos', '0005_retrojuego_namefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retrojuego',
            name='cover',
            field=models.ImageField(blank=True, upload_to='retrogames/covers', verbose_name='Carátula'),
        ),
        migrations.AlterField(
            model_name='retrojuego',
            name='date_released',
            field=models.DateField(blank=True, verbose_name='Fecha de Publicación'),
        ),
        migrations.AlterField(
            model_name='retrojuego',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='retrojuego',
            name='developer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='opciones.Developer', verbose_name='Desarrollador'),
        ),
        migrations.AlterField(
            model_name='retrojuego',
            name='extension',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='opciones.Extension', verbose_name='Formato de Archivo'),
        ),
        migrations.AlterField(
            model_name='retrojuego',
            name='genre',
            field=models.ManyToManyField(blank=True, to='opciones.Genre', verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='retrojuego',
            name='languages',
            field=models.ManyToManyField(blank=True, to='opciones.Language', verbose_name='Idiomas'),
        ),
        migrations.AlterField(
            model_name='retrojuego',
            name='namefile',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nombre del archivo ejecutable'),
        ),
        migrations.AlterField(
            model_name='retrojuego',
            name='original_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Título Original'),
        ),
        migrations.AlterField(
            model_name='retrojuego',
            name='publisher',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='opciones.Produced', verbose_name='Productora'),
        ),
        migrations.AlterField(
            model_name='retrojuego',
            name='screen_four',
            field=models.ImageField(blank=True, upload_to='retrogames/screens', verbose_name='Captura 4'),
        ),
        migrations.AlterField(
            model_name='retrojuego',
            name='screen_one',
            field=models.ImageField(blank=True, upload_to='retrogames/screens', verbose_name='Captura 1'),
        ),
        migrations.AlterField(
            model_name='retrojuego',
            name='screen_three',
            field=models.ImageField(blank=True, upload_to='retrogames/screens', verbose_name='Captura 3'),
        ),
        migrations.AlterField(
            model_name='retrojuego',
            name='screen_two',
            field=models.ImageField(blank=True, upload_to='retrogames/screens', verbose_name='Captura 2'),
        ),
        migrations.AlterField(
            model_name='retrojuego',
            name='serial_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='Número de Serie'),
        ),
        migrations.AlterField(
            model_name='retrojuego',
            name='support',
            field=models.CharField(blank=True, choices=[('CAR', 'Cartucho'), ('CD', 'CD-ROM'), ('DVD', 'DVD'), ('GD', 'GD-ROM'), ('UMD', 'UMD'), ('TA', 'Tarjeta')], max_length=10, verbose_name='Soporte'),
        ),
        migrations.AlterField(
            model_name='retrojuego',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Título'),
        ),
    ]
